let value = true;
alert(typeof value);
value = String(value);
alert(typeof value);
alert("6"/"2");
let str = "123";
alert(typeof str);
let num = Number(str);
alert(typeof num);
let age = Number("an arbitary string instead of a number");
alert(age);
alert(Number("123"));
alert(Number("123z"));
alert(Number(true));
alert(Number(false));
alert(Boolean(1));
alert(Boolean(0));
alert(Boolean("0"));
alert(Boolean(""));